spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        # ????????8
        max-active: 1024
        # ??????????????????-1ms
        max-wait: 10000ms
        # ?????????8
        max-idle: 200
        # ?????????0
        min-idle: 5
          #????
    sentinel:
            #?????
      master: mymaster
            #??
      nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381

