server:
# 端口号
  port: 8001
spring:
  application:
    name: dubbo
  dubbo:
# 开启dubbo
    server: true
#应用信息
    application:
      name: provider
# 注册中心地址
    registry:
      address: multicast://224.5.6.7:1234
    protocol:
#协议名
      name: dubbo
#协议端口
      port: 20880
#扫描包的位置
    scan: com.xxxx.provider.service