server:
# 端口号，防止端口被占用
  port: 8002
spring:
  application:
    name: dubbo
  dubbo:
#应用信息
    application:
      name: consumer
# 注册中心地址
    registry:
      address: multicast://224.5.6.7:1234
    protocol:
#协议名
      name: dubbo
#协议端口
      port: 20880
#扫描包的位置
    scan: com.xxxx.consumer